[package]
name = "rust-move-s3-obj"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
aws-config = "1.5.4"
aws-sdk-s3 = "1.41.0"
clap = { version = "4.5.9", features = ["derive"] }
aws-types = "1.3.3"